### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by zorun** [lojban/jbofihe#3]
Hi,

It's nice to see that there is some activity!

You should add a git tag, such as "v0.40", so that github generates tarballs.  Also, there is probably a way to remove the annoying "forked from rc0/jbofihe" message: look in the github settings. Right now, it does not look like this is the primary repository.

**Comment by zorun** [comment]
Also, I think you should import the issues from https://github.com/rc0/jbofihe/issues

**Comment by KSFT** [comment]
I've contacted GitHub support about converting this to a regular repo. There are only three issues on the old repo, so I'm not sure it's worth it to move them over.

**Comment by rlpowell** [comment]
Hey zorun, can you point your repo to this one in the README the way I got rc0 to do?  https://github.com/rc0/jbofihe/blob/master/README

**Comment by rlpowell** [comment]
KSFT: Yes please, conversion to appearing to be the top-level repo would be great and I have *no* idea how to do it and now that we have https://github.com/rc0/jbofihe/blob/master/README it should be easy to convince them that that's the right thing.

**Comment by rlpowell** [comment]
I can "import" the issues by copying them manually; I'll do that.

**Comment by KSFT** [comment]
Most of the points have been addressed. All that remains is tagging a release, which can be done once the current version is a good one to tag, but it doesn't seem useful to have an issue open for that.
